version: "3.3"
services: 
    backendapp:
        build: .
        ports: 
            - "80:80"
        depends_on: 
            - mysql
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: 'abc123'
            MYSQL_USER: 'mysql'
            MYSQL_PASSWORD: 'abc123'
            MYSQL_DATABASE: 'backendapp'
        volumes: 
            - mydb:/var/lib/mysql
volumes:
    mydb: